<a href="https://colab.research.google.com/github/Mamun-75/Python-For-Data-Science-and-Machine-Learning/blob/main/numpy_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np

In [7]:
arr = np.arange(0,11)

## basic arithmatic operation

In [8]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [9]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [14]:
arr * 100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [15]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [16]:
 1/ 0  ##  In normal arithmatic operation it gives an error,

ZeroDivisionError: division by zero

In [21]:
arr / arr  ## but in numpy it gives a nan warning instead of error

/tmp/ipykernel_2656/2586996425.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr  ## but in numpy it gives a nan warning instead of error


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [23]:
 1/arr   ## it will show an infinity value warning

/tmp/ipykernel_2656/1513963493.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr   ## it will show an infinity value warning


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [24]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [25]:
## universal array function

In [26]:
np.sqrt(arr)  ##square root

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [27]:
np.exp(arr)  ## exponential

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [29]:
np.log(arr)   # it will show an waring of negetive infinity for log(0)

/tmp/ipykernel_2656/1627229066.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)   # it will show an waring of negetive infinity for log(0)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [30]:
np.max(arr)

np.int64(10)

In [31]:
arr.max()  # same

np.int64(10)

In [32]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [33]:
## detailed universal function list for numpy is available in online