In [58]:
# numpy array is the main way to use numpy libraries

In [59]:
# numpy array essentially come in two flavours, one dimentional verctor , and two dimenitonal metrices

In [57]:
# lets create numpy array

In [60]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [61]:
import numpy as np

In [62]:
arr = np.array(my_list)  ## so we can cast a normal python list into array

In [63]:
arr

array([1, 2, 3])

In [64]:
##two dimensional array

In [65]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [66]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
## this is how we can cast a normal python lists,  or a list of lists to a numpy array

In [68]:
## usually we use numpys own built in generation method to actually create arrays a lot faster and a lot simpler

In [69]:
## some common way to create a numpy array

In [70]:
np.arange(0,11) ## np.arange(start, end)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [71]:
# we can also add step size here as 3rd argument
np.arange(0,11,2) ## np.arange(start, end,step size)

array([ 0,  2,  4,  6,  8, 10])

In [72]:
#so arange is one of the most useful functions for quickly generating an array using numpy

In [73]:
# we can create other specific types of arrays in numpy

In [74]:
# arrays of all zeros
np.zeros(3)

array([0., 0., 0.])

In [75]:
np.zeros((5,5)) ## the tuple inside zeros function represents( number_of_rows, number_of_colums)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [76]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [77]:
## array of just pure ones
np.ones(3) #1D

array([1., 1., 1.])

In [78]:
np.ones((3,4)) #2D

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [79]:
## linspace (start, end, n evenly spaced points between start and end)
np.linspace(0,5,10)    #remember the 3rd argument if different from arange function

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [80]:
## identity matrix, it will help us dealing with linear algebra problems

In [81]:
# it takes a single argument and create a 2D square matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [82]:
##  random numbers !!!! most important
np.random.rand(5)  # this is going to create an arry of the given shape we pass in
                    ## and its going to populate with random samples from a uniform distribution over 0 to 1

array([0.61683389, 0.36002709, 0.59741349, 0.48323353, 0.77717437])

In [83]:
np.random.rand(5,5) ## for 2D

array([[0.91154099, 0.70108988, 0.19139772, 0.73859824, 0.94755831],
       [0.03427803, 0.56714181, 0.12547061, 0.84156994, 0.51162038],
       [0.39714336, 0.13271423, 0.5352039 , 0.84067366, 0.06786316],
       [0.15271068, 0.58848936, 0.51282792, 0.04784794, 0.64707972],
       [0.01767094, 0.17916922, 0.94548241, 0.97049144, 0.90976936]])

In [84]:
np.random.randn(2) ##if we want to return a sample or many samples from the standard normal distribution or a gaussian distribution instead of using rand we use randn

array([ 0.72131592, -1.46861369])

In [85]:
np.random.randn(4,4)

array([[ 1.27597557, -0.52818963, -0.38505873,  0.24017233],
       [ 1.61421048, -0.60789201, -0.97009686,  1.67386857],
       [ 1.53713673, -0.42035994,  0.38295577,  0.29453511],
       [ 0.73250061,  0.52808564, -1.13714758,  0.70565039]])

In [86]:
## A uniform distribution has a flat, rectangular shape where every value in a set range has an equal chance of happening. A normal distribution has a symmetric, bell-shaped curve where values near the middle mean are most common, and values far from the center are rare

In [87]:
## rand int
np.random.randint(1,100) # here , 1 is inclusive and 100 is exclusive,"Inclusive" (low) means the starting value can be included in the results.
                         ## and "Exclusive" (high) means the ending value cannot be included in the results.

29

In [88]:
# we can pass a third argument  = number of random number,,,,
#inclusive is the low end, exclusive in the high end
np.random.randint(1,100,10)

array([ 8, 86, 96, 93, 66, 64, 85, 34, 62, 42])

In [89]:

## lets discuss a few useful attributes and methods of an array


In [90]:
arr = np.arange(25)

In [91]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [92]:
ranarr = np.random.randint(0,50,10)

In [93]:
ranarr

array([ 6,  7, 25, 39,  2, 30, 27, 48, 20, 20])

In [94]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [95]:
ranarr.max()

np.int64(48)

In [96]:
ranarr.min()

np.int64(2)

In [98]:
ranarr.argmax() ## it will return index location of the max value

np.int64(7)

In [99]:
ranarr.argmin() ## it will return index location of the min value

np.int64(4)

In [100]:
arr.shape

(25,)

In [101]:
## its indicating arr is one dimensional vector

In [103]:
arr = arr.reshape(5,5)

In [105]:
arr.shape

(5, 5)

In [106]:
## data type
arr.dtype

dtype('int64')

In [107]:
## if we dont want to write np.random. each time, we can use this
from numpy.random import randint

In [110]:
randint(2,10,5)

array([9, 9, 6, 4, 5])