<a href="https://colab.research.google.com/github/Mamun-75/Python-For-Data-Science-and-Machine-Learning/blob/main/numpy_indexing_and_selection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
##indexing and selection


In [5]:
import numpy as np

In [6]:
arr = np.arange(0,11)

In [7]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr[8]

np.int64(8)

In [9]:
arr[1:5] ##slice notation

array([1, 2, 3, 4])

In [10]:
arr [0:5]

array([0, 1, 2, 3, 4])

In [11]:
arr [0:6]

array([0, 1, 2, 3, 4, 5])

In [12]:
arr[5:] ## grab everything beyond index 5

array([ 5,  6,  7,  8,  9, 10])

In [13]:
## numpy arrays differ from a normal python list because of their ability to broadcast
arr[0:5]=100

In [14]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [15]:
arr = np.arange(0,11)

In [16]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
slice_of_arr = (arr[0:6])

In [18]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [19]:
slice_of_arr[:]

array([0, 1, 2, 3, 4, 5])

In [20]:
slice_of_arr[:]=99

In [21]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [22]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [23]:
## so slice_of_arr is not a copy of arr,
## its just a reference of the original arr,
## thats why when we broadcast 99 in slice_of_arr , it actually changed the original arr

In [24]:
# so if we want to copy an array,
arr_copy = arr.copy()

In [25]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [26]:
arr_copy[:] = 100

In [27]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [28]:
arr  ## now it hasn't changed

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [29]:
## for 2D array

In [30]:
import numpy as np

In [31]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [32]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [33]:
## there are 2 general formats for grabbing an element from a 2D array
# 1. double bracket format
# 2. single bracket format

In [34]:
arr_2d[1][2]

np.int64(30)

In [35]:
arr_2d[1,2] # recommended

np.int64(30)

In [36]:
## if we want to grab a section instead of a single element
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [38]:
arr_2d[:2, 1:]   ## [ rows, cols]

array([[10, 15],
       [25, 30]])

In [39]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [42]:
arr_2d[1:, 1:]

array([[25, 30],
       [40, 45]])

In [43]:
## lets move on to the conditional selection which we will use more in this series

In [44]:
arr = np.arange(1,11)

In [45]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
bool_arr = arr > 5   ## comparision operator here actually return an array of boolean value

In [51]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [53]:
arr[bool_arr]   ## this return value only where boolean array is true

array([ 6,  7,  8,  9, 10])

In [55]:
## we will use this syntax all the time
arr = np.arange(1,11)

arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [57]:
arr[arr<3]  ## inside the bracket we actually passing boolean values here

array([1, 2])

In [58]:
## practice
arr_2d = np.arange(50).reshape(5,10)

In [59]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [60]:
## lets grab 13,14 here
arr_2d[1,3:5]

array([13, 14])

In [62]:
## lets grab the the subsection including 13,14,23,24
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])